on:
    pull_request: null
    push:
        branches:
            - '*.*'

name: coding-standards

jobs:
    psalm:
        uses: spiral/gh-actions/.github/workflows/cs.yml@master
        with:
            os: >-
                ['ubuntu-latest']
            php: >-
                ['8.1']
